<?php

namespace Cinetic\FranjasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FranjaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FranjaRepository extends EntityRepository
{
}
