<?php

namespace Cinetic\ReservaBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Validator\Constraints\Null;

/**
 * ReservaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservaRepository extends EntityRepository
{
    /**
     * Busca los dias reservados según un mes y un año determinados.
     */
    public function findAllFromYearAndMonth($year, $month=null)
    {
        //formato la string para utilizarla en el operador like
        if(($month==10) | ($month==11) | ($month==12)) {
            $string = $year.'-'.$month.'%';
        }
        elseif(is_null($month)) {
            $string = $year.'%';
        }
        else {
            $string = $year.'-0'.$month.'%';
        }
        return $this->getEntityManager()
            ->createQuery(
                'SELECT o
                FROM CineticReservaBundle:Reserva o
                WHERE o.dia LIKE :string
                ORDER BY o.id ASC
                '
            )
            ->setParameter('string',$string)
            ->getResult();
    }
}
