<?php

namespace Cinetic\DiaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiaRepository extends EntityRepository
{
    /**
     * Busca y ordena los dias según su Id en la base de datos.
     */
    public function findAllOrderedById()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT d FROM CineticDiaBundle:Dia d ORDER BY d.id ASC'
            )
            ->getResult();
    }
}
